Extracting a showAdaptiveDateTimePickerDialog from the DateField main…
GaspardMerten/date_field pull request #71
Opened 2024-05-31 18:26 UTC by GaspardMerten

… widget to allow standalone usage of the Dialog while cleaning up the widget itself.

- Restructuring the project for better readability and maintainability.
- Bumping version to 5.2.0
- Updating the showcase example

2024-05-31 18:35 UTC, torbenkeller commented
I will have a look tomorrow

2024-06-02 15:18 UTC, torbenkeller requested changes

2024-06-02 15:18 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
> +        use24hFormat: true,
Why are you fixing this to true?

2024-06-02 15:18 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
> +    );
please use `return` instead of `else` to increase readability

2024-06-02 15:18 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
> +Future<TimeOfDay?> showMaterialTimePicker({
If you want to keep the function public, then please document it

2024-06-02 15:18 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
> +Future<DateTime?> showMaterialDatePicker({
If you want to keep the function public, then please document it

2024-06-02 15:18 UTC, torbenkeller commented on README.md
> +- **showAdaptiveDateTimePickerDialog**: A function that shows a date and/or time picker dialog based on the platform,
we should provide a simple example in the readme how to use the global functions

2024-06-02 15:18 UTC, torbenkeller commented on pubspec.yaml
> +description: A field widget to allow users to select a date using platforms date picker dialogs.
I think having the term `form` in it is important for SEO on pub dev. I would go with something like this:

> A FormField widget to select DateTime values using adaptive Material and Cupertino DateTime Pickers. It also provides global functions to provide the pickers.

2024-06-03 16:55 UTC, GaspardMerten commented on lib/src/widgets/adaptive_dialog.dart
> +        data: MediaQuery.of(context).copyWith(alwaysUse24HourFormat: true),
Rolleback, did not do on purpose.

2024-06-03 17:00 UTC, GaspardMerten commented on lib/src/widgets/adaptive_dialog.dart
Agreed! I went for `showCupertinoDateTimePicker`  for better consistency in the naming (or was there a reason for the extra Modal?)

2024-06-03 17:00 UTC, GaspardMerten commented on lib/src/widgets/cupertino_date_picker.dart
> +import '../../date_field.dart';
nop, I have this convention in on of my project, got out of control :))

2024-06-03 17:03 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
For me it is a modal sheet, but you can also omit it

2024-06-03 17:25 UTC, GaspardMerten commented
@torbenkeller All is taken care of.

2024-06-03 17:26 UTC, GaspardMerten commented on pubspec.yaml
> +description: A field widget to allow users to select a date using platforms date picker dialogs.
I just added a space (I don't know how to search engine of pub.dev work), but in general, I think it is best to separate the keywords (even if they are a class..)

2024-06-03 17:50 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
> +import 'dart:io';
Did you test the widget on web? `dart:io` is not available on web

2024-06-03 17:50 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
> +Future<TimeOfDay?> showMaterialTimePicker({
I would make this private as `_showMaterialDatePicker` because it is only a composing the already existing function

2024-06-04 07:49 UTC, GaspardMerten commented on lib/src/widgets/adaptive_dialog.dart
> +import 'dart:io';
It seems it was already there in previous versions.

2024-06-04 08:00 UTC, GaspardMerten commented on lib/src/widgets/adaptive_dialog.dart
> +import 'dart:io';
I am now using the target Platform from the context. I also added a way for the user to override the behaviour directly.

2024-06-04 10:20 UTC, torbenkeller commented on lib/src/widgets/adaptive_dialog.dart
> +import 'dart:io';
I see, then I would keep it as it was. I spent much time on developing this method, because the date format should align to the internal systems region. I.e. if you are living in Germany and set your phone language to English, then you want the date format in 24 hour format. Unfortunately there are some bugs in the intl package determining the systems region correctly on other platforms than iOS and Android. Therefore I would keep using `dart:io` `Platform` checks. Especially the web check is important, because on web, you can not get teh systems region

2024-06-04 10:25 UTC, torbenkeller commented on lib/src/widgets/form_field.dart
> +    bool? use24HoursFormat,
I would remove this. The determination is smart enough and the users will make it probably worse

2024-06-04 10:26 UTC, torbenkeller commented on lib/src/widgets/field.dart
> +    bool? use24HoursFormat,
I would remove this. The determination is smart enough and the users will make it probably worse

2024-06-04 12:26 UTC, GaspardMerten commented on lib/src/widgets/adaptive_dialog.dart
> +import 'dart:io';
Agreed, done!

2024-06-04 12:27 UTC, merged

2024-06-04 12:28 UTC, GaspardMerten commented
Thank you, @torbenkeller, for the extensive review! v5.2.0 is now live